plugins {
    id 'java-library'
    id 'net.neoforged.moddev'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    // Specify the version of NeoForge to use.
    version = libs.versions.neoforge.get()

    runs {
        client {
            client()
        }

        server {
            server()
        }
    }

    mods {
        syringe_testmod {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    compileOnly cLibs.bundles.compileonly
    annotationProcessor cLibs.bundles.annotationprocessor

    implementation(project(':')) {
        capabilities {
            requireFeature('fml')
        }
    }
}
