plugins {
    id 'java-library'
    id 'syringe.jarjar'
    id 'signing'
    id 'dev.lukebemish.managedversioning'
    id 'maven-publish'
}

group = 'dev.lukebemish'

managedVersioning {
    versionFile.set project.file('version.properties')
    versionPRs()
    versionSnapshots()

    gitHubActions {
        snapshot {
            prettyName.set 'Snapshot'
            workflowDispatch.set(true)
            onBranches.add 'main'
            gradleJob {
                buildCache()
                cacheReadOnly.set false
                javaVersion.set '21'
                name.set 'build'
                gradlew 'Build', 'build'
                gradlew 'Publish', 'publish'
                mavenSnapshot('github')
            }
        }
        release {
            prettyName.set 'Release'
            workflowDispatch.set(true)
            gradleJob {
                buildCache()
                javaVersion.set '21'
                name.set 'build'
                step {
                    setupGitUser()
                }
                readOnly.set false
                gradlew 'Tag Release', 'tagRelease'
                gradlew 'Build', 'build'
                step {
                    run.set 'git push && git push --tags'
                }
                recordVersion 'Record Version', 'version'
                dependencySubmission()
            }
            gradleJob {
                buildCache()
                javaVersion.set '21'
                name.set 'publish'
                needs.add('build')
                tag.set('${{needs.build.outputs.version}}')
                gradlew 'Publish', 'publish', 'closeAndReleaseSonatypeStagingRepository'
                sign()
                mavenCentral()
                mavenStaging('github')
            }
        }
        build_pr {
            prettyName.set 'Build PR'
            pullRequest.set(true)
            gradleJob {
                javaVersion.set '21'
                name.set 'build'
                gradlew 'Build', 'build'
                gradlew 'Publish', 'publish'
                pullRequestArtifact()
            }
        }
        publish_pr {
            prettyName.set 'Publish PR'
            publishPullRequestAction(
                'github',
                "${project.group.replace('.', '/')}/${project.name}",
                'Build PR'
            )
        }
    }

    apply()
}

println "Version: ${project.version}"

sourceSets {
    neoforge {}
    fabric {}
    common {}
}

java {
    withSourcesJar()
    withJavadocJar()
    toolchain.languageVersion.set JavaLanguageVersion.of(21)
    registerFeature('neoforge') {
        usingSourceSet(sourceSets.neoforge)
    }
    registerFeature('fabric') {
        usingSourceSet(sourceSets.fabric)
    }
    registerFeature('common') {
        usingSourceSet(sourceSets.common)
        withSourcesJar()
        withJavadocJar()
    }
}

configurations {
    dependencyScope('neoforgeJarJar')
    resolvable('neoforgeJarJarClasspath') {
        extendsFrom configurations.neoforgeJarJar
        transitive = false
    }

    dependencyScope('fabricBundle')
    resolvable('fabricBundleClasspath') {
        extendsFrom configurations.fabricBundle
    }
}

dependencies {
    compileOnly cLibs.bundles.compileonly
    annotationProcessor cLibs.bundles.annotationprocessor
    api libs.jakarta.inject.api
    implementation libs.asm

    testCompileOnly cLibs.bundles.compileonly
    testAnnotationProcessor cLibs.bundles.annotationprocessor
    testImplementation project(':')
    testImplementation libs.jakarta.inject.tck

    testImplementation libs.junit.jupiter
    testCompileOnly libs.junit.junit
    testRuntimeOnly libs.junit.vintage.engine
    testRuntimeOnly libs.junit.platform.launcher

    commonCompileOnly cLibs.bundles.compileonly
    commonAnnotationProcessor cLibs.bundles.annotationprocessor

    commonApi project(':')

    neoforgeCompileOnly cLibs.bundles.compileonly
    neoforgeAnnotationProcessor cLibs.bundles.annotationprocessor

    neoforgeImplementation libs.fml
    neoforgeApi project(':')

    neoforgeJarJar project(':syringe-neoforge-attachment')
    neoforgeJarJar project(':')
    neoforgeJarJar libs.jakarta.inject.api

    fabricCompileOnly cLibs.bundles.compileonly
    fabricAnnotationProcessor cLibs.bundles.annotationprocessor
    // We shadow the attachment mod instead of jar-in-jaring it, to avoid dealing with loom's issues with stripping nested jars

    fabricImplementation libs.fabric.loader
    fabricApi project(':')
    fabricBundle project(':syringe-fabric-attachment')
}

tasks.named('jar', Jar) {
    manifest {
        attributes (
            'FMLModType': 'LIBRARY',
            'Implementation-Version': project.version as String,
            'Automatic-Module-Name': 'dev.lukebemish.syringe'
        )
    }
}

tasks.named('neoforgeJar', Jar) {
    from sourceSets.common.output
    manifest {
        attributes (
            'FMLModType': 'LIBRARY',
            'Implementation-Version': project.version as String,
            'Automatic-Module-Name': 'dev.lukebemish.syringe.neoforge'
        )
    }
}

tasks.register('fabricPrepareBundle', UnzipAllTask) {
    inputArchives.from configurations.fabricBundleClasspath
}

tasks.named('fabricJar', Jar) {
    from(tasks.fabricPrepareBundle.outputDirectory) {
        exclude('META-INF/MANIFEST.MF')
    }
    from sourceSets.common.output
    manifest {
        from tasks.fabricPrepareBundle.outputDirectory.file('META-INF/MANIFEST.MF')
        attributes (
            'Implementation-Version': project.version as String,
            'Automatic-Module-Name': 'dev.lukebemish.syringe.fabric'
        )
    }
}

tasks.named('neoforgeJarJar', JarJarTask) {
    from(configurations.neoforgeJarJarClasspath)
}

test {
    useJUnitPlatform()

    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
        showCauses = true
        showStackTraces = true
        events = ['passed', 'failed', 'skipped']
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            managedVersioning.publishing.sign(signing, it)
            managedVersioning.publishing.pom(it, 'syringe', 'LGPL-3.0-only')
            pom {
                name = 'syringe'
                description = 'Dependency injection framework supporting injection by implementing abstract getters'
            }

            from components.java
        }
    }
}

managedVersioning.publishing.mavenStaging(publishing)
managedVersioning.publishing.mavenCentral()
managedVersioning.publishing.mavenPullRequest(publishing)
managedVersioning.publishing.mavenSnapshot(publishing)
