plugins {
    id 'java-library'
    id 'syringe.jarjar'
}

group = 'dev.lukebemish'
// TODO: managed versioning
version = '0.1.0'

sourceSets {
    neoforge {}
    fabric {}
    common {}
}

java {
    withSourcesJar()
    withJavadocJar()
    toolchain.languageVersion.set JavaLanguageVersion.of(21)
    registerFeature('neoforge') {
        usingSourceSet(sourceSets.neoforge)
    }
    registerFeature('fabric') {
        usingSourceSet(sourceSets.fabric)
    }
    registerFeature('common') {
        usingSourceSet(sourceSets.common)
        disablePublication()
    }
}

configurations {
    dependencyScope('neoforgeJarJar')
    resolvable('neoforgeJarJarClasspath') {
        extendsFrom configurations.neoforgeJarJar
        transitive = false
    }

    dependencyScope('fabricBundle')
    resolvable('fabricBundleClasspath') {
        extendsFrom configurations.fabricBundle
    }
}

dependencies {
    compileOnly cLibs.bundles.compileonly
    annotationProcessor cLibs.bundles.annotationprocessor
    api libs.jakarta.inject.api
    implementation libs.asm

    testCompileOnly cLibs.bundles.compileonly
    testAnnotationProcessor cLibs.bundles.annotationprocessor
    testImplementation project(':')
    testImplementation libs.jakarta.inject.tck

    testImplementation libs.junit.jupiter
    testCompileOnly libs.junit.junit
    testRuntimeOnly libs.junit.vintage.engine
    testRuntimeOnly libs.junit.platform.launcher

    commonCompileOnly cLibs.bundles.compileonly
    commonAnnotationProcessor cLibs.bundles.annotationprocessor

    commonApi project(':')

    neoforgeCompileOnly cLibs.bundles.compileonly
    neoforgeAnnotationProcessor cLibs.bundles.annotationprocessor

    neoforgeImplementation libs.fml
    neoforgeApi project(':')

    neoforgeJarJar project(':syringe-neoforge-attachment')
    neoforgeJarJar project(':')
    neoforgeJarJar libs.jakarta.inject.api

    fabricCompileOnly cLibs.bundles.compileonly
    fabricAnnotationProcessor cLibs.bundles.annotationprocessor
    // We shadow the attachment mod instead of jar-in-jaring it, to avoid dealing with loom's issues with stripping nested jars

    fabricImplementation libs.fabric.loader
    fabricApi project(':')
    fabricBundle project(':syringe-fabric-attachment')
}

tasks.named('jar', Jar) {
    manifest {
        attributes (
            'FMLModType': 'LIBRARY',
            'Implementation-Version': project.version as String,
            'Automatic-Module-Name': 'dev.lukebemish.syringe'
        )
    }
}

tasks.named('neoforgeJar', Jar) {
    from sourceSets.common.output
    manifest {
        attributes (
            'FMLModType': 'LIBRARY',
            'Implementation-Version': project.version as String,
            'Automatic-Module-Name': 'dev.lukebemish.syringe.neoforge'
        )
    }
}

tasks.register('fabricPrepareBundle', UnzipAllTask) {
    inputArchives.from configurations.fabricBundleClasspath
}

tasks.named('fabricJar', Jar) {
    from(tasks.fabricPrepareBundle.outputDirectory) {
        exclude('META-INF/MANIFEST.MF')
    }
    from sourceSets.common.output
    manifest {
        from tasks.fabricPrepareBundle.outputDirectory.file('META-INF/MANIFEST.MF')
        attributes (
            'Implementation-Version': project.version as String,
            'Automatic-Module-Name': 'dev.lukebemish.syringe.fabric'
        )
    }
}

tasks.named('neoforgeJarJar', JarJarTask) {
    from(configurations.neoforgeJarJarClasspath)
}

test {
    useJUnitPlatform()

    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
        showCauses = true
        showStackTraces = true
        events = ['passed', 'failed', 'skipped']
    }
}
