plugins {
    id 'java-library'
}

group = 'dev.lukebemish'
// TODO: managed versioning
version = '0.1.0'

java {
    withSourcesJar()
    withJavadocJar()
    toolchain.languageVersion.set JavaLanguageVersion.of(21)
}

dependencies {
    compileOnly cLibs.bundles.compileonly
    annotationProcessor cLibs.bundles.annotationprocessor
    api libs.jakarta.inject.api
    implementation libs.asm

    testCompileOnly cLibs.bundles.compileonly
    testAnnotationProcessor cLibs.bundles.annotationprocessor
    testImplementation project(':')
    testImplementation libs.jakarta.inject.tck

    testImplementation libs.junit.jupiter
    testCompileOnly libs.junit.junit
    testRuntimeOnly libs.junit.vintage.engine
    testRuntimeOnly libs.junit.platform.launcher
}

test {
    useJUnitPlatform()

    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
        showCauses = true
        showStackTraces = true
        events = ['passed', 'failed', 'skipped']
    }
}
