pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url "https://maven.lukebemish.dev/releases/"
        }
        maven {
            name = "neoforged"
            url = "https://maven.neoforged.net/releases/"
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
    id 'dev.lukebemish.conventions' version '0.1.11'
    id 'net.neoforged.moddev.repositories' version '2.0.78'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            url = "https://maven.lukebemish.dev/releases/"
        }
    }

    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
}

rootProject.name = 'syringe'

include(':syringe-neoforge-attachment')
include(':syringe-fabric-attachment')

project(':syringe-neoforge-attachment').projectDir = file('neoforge-attachment')
project(':syringe-fabric-attachment').projectDir = file('fabric-attachment')

include(':test-neoforge')
