modLoader="javafml"
loaderVersion="[6,)"
license="LGPL-3.0-or-later"

[[mods]]
modId="dev.lukebemish.syringe.neoforge.attachment"
version="${version}"
displayName="Syringe Neoforge Attachment"
description="Game-Layer Attachment Point for Syringe's Neoforge Compat"
authors="Luke Bemish"

[[dependencies."dev.lukebemish.syringe.neoforge.attachment"]]
modId="neoforge"
type="required"
versionRange="[${neoforgeVersion}]"
ordering="NONE"
side="BOTH"


