plugins {
    id 'java-library'
    id 'net.neoforged.moddev'
    id 'dev.lukebemish.managedversioning'
}

group = 'dev.lukebemish'

managedVersioning {
    versionFile.set rootProject.isolated.projectDirectory.file('version.properties')
    gitWorkingDir.set rootProject.isolated.projectDirectory
    versionPRs()
    versionSnapshots()

    apply()
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    // Specify the version of NeoForge to use.
    version = libs.versions.neoforge.get()
}

dependencies {
    compileOnly cLibs.bundles.compileonly
    annotationProcessor cLibs.bundles.annotationprocessor

    compileOnly(project(':')) {
        capabilities {
            requireFeature('neoforge')
        }
    }

    compileOnly(project(':')) {
        capabilities {
            requireFeature('common')
        }
    }
}

tasks.named('processResources', ProcessResources) {
    var replaceProperties = [
        neoforgeVersion: libs.versions.neoforge.get(),
        version: version as String
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar) {
    manifest {
        attributes (
            'Implementation-Version': project.version as String,
            'Automatic-Module-Name': 'dev.lukebemish.syringe.neoforge.attachment'
        )
    }
}
