plugins {
    id 'java-library'
    id 'fabric-loom'
}

group = 'dev.lukebemish'
// TODO: managed versioning
version = '0.1.0'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

dependencies {
    compileOnly cLibs.bundles.compileonly
    annotationProcessor cLibs.bundles.annotationprocessor

    compileOnly(project(':')) {
        capabilities {
            requireFeature('common')
        }
    }

    compileOnly(project(':')) {
        capabilities {
            requireFeature('fabric')
        }
    }

    minecraft libs.minecraft
    mappings loom.officialMojangMappings()

    modCompileOnly libs.fabric.loader

    include project(':')
    include libs.jakarta.inject.api
}

tasks.named('processResources', ProcessResources) {
    var replaceProperties = [
        fabricLoaderVersion: libs.versions.fabric.loader.get(),
        minecraftVersion: libs.versions.minecraft.get(),
        version: version as String
    ]
    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json']) {
        expand replaceProperties
    }
}
